### ISSUE TITLE
subrepositories is private or protected

### ISSUE THREAD

**Issue by tigrazone** [santaclose/ste#1]
when I do git clone --recursive or git submodule update I have error:
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:santaclose/ImGuiColorTextEdit.git' into submodule path 'C:/msys64/home/user/from-git/scex/vendor/ImGuiColorTextEdit' failed
Failed to clone 'vendor/ImGuiColorTextEdit' a second time, aborting
for all submodules.
Can you fix it?

**Comment by santaclose** [comment]
right. I'll take a look. for now you can replace the reference with an http link

**Comment by tigrazone** [comment]
"you can replace the reference with an http link"
how?

**Comment by santaclose** [comment]
You should just be able to edit the .gitmodules file to update the URL

**Comment by tigrazone** [comment]
after change to http I have new issue
user@WIN-BMGIMTPHQ1L MINGW64 ~/from-git/scex
$ premake5 gmake2
Error: ...s64/home/user/from-git/scex/vendor/GLFW/premake5.lua:30: attempt to call global 'systemver
sion' (a nil value)

trying to build with MinGW and trying to build with vs - same issue

**Comment by santaclose** [comment]
I guess you are using the batch script. There might be something wrong with the reference to the glfw submodule, but it should reference the latest version of my fork that is also on github. I'll take a look

**Comment by santaclose** [comment]
also, make sure you cloned the submodules. I think the command is: `git submodule update --init --recursive`

**Comment by tigrazone** [comment]
I changed urls to https and git submodule update. All submodules updated but error with 
scex/vendor/GLFW/premake5.lua:30: attempt to call global 'systemversion' (a nil value) still exists

**Comment by santaclose** [comment]
I just cloned the repository again and everything worked fine for me. Make sure you use the right version of premake. 
https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-windows.zip

**Comment by tigrazone** [comment]
I'm trying to build on linux with premake 5.0.0-beta2 and have new errors ;-)
==== Building scex (release) ====
Creating bin-int/Release-linux-x86_64/scex
DirectoryFinder.cpp
src/panels/DirectoryFinder.cpp: In constructor ‘DirectoryFinder::DirectoryFinder(const std::string&, OnResultClickCallback, OnResultFoundCallback, OnSearchFinishedCallback, OnFocusedCallback, int, int)’:
src/panels/DirectoryFinder.cpp:22:56: error: cast from ‘DirectoryFinder*’ to ‘int’ loses precision [-fpermissive]
   22 |         panelName = "Folder search##" + std::to_string((int)this);
      |                                                        ^~~~~~~~~
src/panels/DirectoryFinder.cpp: In member function ‘void DirectoryFinder::Find()’:
src/panels/DirectoryFinder.cpp:129:31: error: no matching function for call to ‘std::basic_ifstream<char>::open(std::wstring)’
  129 |                 fileInput.open(Utils::Utf8ToWstring(filePath));
      |                 ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/panels/DirectoryFinder.cpp:5:
/usr/include/c++/12/fstream:723:9: note: candidate: ‘template<class _Path> std::_If_fs_path<_Path, void> std::basic_ifstream<_CharT, _Traits>::open(const _Path&, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>]’
  723 |         open(const _Path& __s, ios_base::openmode __mode = ios_base::in)
      |         ^~~~
/usr/include/c++/12/fstream:723:9: note:   template argument deduction/substitution failed:
/usr/include/c++/12/fstream: In substitution of ‘template<class _Path> std::_If_fs_path<_Path, void, decltype (declval<_Path&>().make_preferred().filename())> std::basic_ifstream<char>::open(const _Path&, std::ios_base::openmode) [with _Path = std::__cxx11::basic_string<wchar_t>]’:
src/panels/DirectoryFinder.cpp:129:17:   required from here
/usr/include/c++/12/fstream:723:9: error: ‘class std::__cxx11::basic_string<wchar_t>’ has no member named ‘make_preferred’
/usr/include/c++/12/fstream:663:7: note: candidate: ‘void std::basic_ifstream<_CharT, _Traits>::open(const char*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::ios_base::openmode]’
  663 |       open(const char* __s, ios_base::openmode __mode = ios_base::in)
      |       ^~~~
/usr/include/c++/12/fstream:663:24: note:   no known conversion for argument 1 from ‘std::wstring’ {aka ‘std::__cxx11::basic_string<wchar_t>’} to ‘const char*’
  663 |       open(const char* __s, ios_base::openmode __mode = ios_base::in)
      |            ~~~~~~~~~~~~^~~
/usr/include/c++/12/fstream:702:7: note: candidate: ‘void std::basic_ifstream<_CharT, _Traits>::open(const std::string&, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::string = std::__cxx11::basic_string<char>; std::ios_base::openmode = std::ios_base::openmode]’
  702 |       open(const std::string& __s, ios_base::openmode __mode = ios_base::in)
      |       ^~~~
/usr/include/c++/12/fstream:702:31: note:   no known conversion for argument 1 from ‘std::wstring’ {aka ‘std::__cxx11::basic_string<wchar_t>’} to ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’}
  702 |       open(const std::string& __s, ios_base::openmode __mode = ios_base::in)
      |            ~~~~~~~~~~~~~~~~~~~^~~
make[1]: *** [scex.make:184: bin-int/Release-linux-x86_64/scex/DirectoryFinder.o] Error 1
make: *** [Makefile:56: scex] Error 2
thr@thr:~/scex$

**Comment by tigrazone** [comment]
tomorrow I will check to build on windows.
on linux I do mv vendor/glfw vendor/GLFW
because premake5 fails with error
Error: cannot open vendor/GLFW: No such file or directory
UPPERCASE is metter

**Comment by santaclose** [comment]
yeah I know it doesn't compile on linux right now. Pending to fix. Windows should be fine with VS
